(node:1492801) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-nosession-45805',
  containerIp: '10.0.3.52',
  mitmPort: 45805,
  autoAccessFixed: 1
}
2024-11-16 16:06:17.218 - [Info] MITM Version: 2
2024-11-16 16:06:17.221 - [Info] Auto Access Enabled: true
2024-11-16 16:06:17.221 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-16 16:06:17.233 - [Info] SSH man-in-the-middle server for 10.0.3.52 listening on 10.0.3.1:45805
2024-11-16 16:13:17.401 - [Debug] [Connection] Attacker connected: 186.31.95.163 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-16 16:13:17.933 - [Debug] [Auth] Attacker 186.31.95.163 trying to authenticate with 'password'
2024-11-16 16:13:17.934 - [Debug] [Auto Access] Attacker: 186.31.95.163, Threshold: 1, Attempts: 1
2024-11-16 16:13:17.934 - [Debug] [Auto Access] Compromising the honeypot
2024-11-16 16:13:17.934 - [Debug] [Auto Access] Adding the following credentials: 'deploy:q1w2e3'
2024-11-16 16:13:18.227 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-16 16:13:18.230 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-16 16:13:18.230 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.52
2024-11-16 16:13:18.340 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-16 16:13:18.664 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-16 16:13:19.239 - [Debug] [Connection] Attacker connected: 186.31.95.163 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-16 16:13:19.777 - [Debug] [Auth] Attacker 186.31.95.163 trying to authenticate with 'password'
2024-11-16 16:13:19.778 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-16 16:13:19.779 - [Debug] [Auth] Attacker: 186.31.95.163 has so far made 1 attempts. Remaining: 5 attempts
2024-11-16 16:13:19.939 - [Debug] [Connection] Attacker closed the connection
2024-11-16 16:13:20.022 - [Debug] [Connection] Attacker connected: 186.31.95.163 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-16 16:13:20.565 - [Debug] [Auth] Attacker 186.31.95.163 trying to authenticate with 'password'
2024-11-16 16:13:20.565 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-16 16:13:20.566 - [Debug] [Auth] Attacker: 186.31.95.163 has so far made 1 attempts. Remaining: 5 attempts
2024-11-16 16:13:20.729 - [Debug] [Connection] Attacker closed the connection
2024-11-16 16:13:20.890 - [Debug] [Connection] Attacker closed connection
2024-11-16 16:13:20.897 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-16 16:13:20.898 - [Debug] [LXC] Container's OpenSSH server closed connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
