(node:2013627) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-nosession-45848',
  containerIp: '10.0.3.157',
  mitmPort: 45848,
  autoAccessFixed: 1
}
2024-11-17 02:01:06.870 - [Info] MITM Version: 2
2024-11-17 02:01:06.873 - [Info] Auto Access Enabled: true
2024-11-17 02:01:06.873 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-17 02:01:06.885 - [Info] SSH man-in-the-middle server for 10.0.3.157 listening on 10.0.3.1:45848
2024-11-17 02:03:47.288 - [Debug] [Connection] Attacker connected: 49.0.116.196 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 02:03:49.871 - [Debug] [Auth] Attacker 49.0.116.196 trying to authenticate with 'password'
2024-11-17 02:03:49.872 - [Debug] [Auto Access] Attacker: 49.0.116.196, Threshold: 1, Attempts: 1
2024-11-17 02:03:49.872 - [Debug] [Auto Access] Compromising the honeypot
2024-11-17 02:03:49.873 - [Debug] [Auto Access] Adding the following credentials: 'postgres:444444'
2024-11-17 02:03:50.176 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-17 02:03:50.178 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-17 02:03:50.178 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.157
2024-11-17 02:03:50.268 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-17 02:03:52.331 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-17 02:03:54.803 - [Debug] [Connection] Attacker connected: 49.0.116.196 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 02:03:57.744 - [Debug] [Auth] Attacker 49.0.116.196 trying to authenticate with 'password'
2024-11-17 02:03:57.745 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-17 02:03:57.745 - [Debug] [Auth] Attacker: 49.0.116.196 has so far made 1 attempts. Remaining: 5 attempts
2024-11-17 02:03:58.739 - [Debug] [Connection] Attacker closed the connection
2024-11-17 02:03:59.150 - [Debug] [Connection] Attacker connected: 49.0.116.196 | Client Identification: SSH-2.0-libssh_0.9.6
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
