(node:1931129) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-nosession-41594',
  containerIp: '10.0.3.218',
  mitmPort: 41594,
  autoAccessFixed: 1
}
2024-11-07 14:14:30.397 - [Info] MITM Version: 2
2024-11-07 14:14:30.399 - [Info] Auto Access Enabled: true
2024-11-07 14:14:30.399 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-07 14:14:30.416 - [Info] SSH man-in-the-middle server for 10.0.3.218 listening on 10.0.3.1:41594
2024-11-07 14:15:12.367 - [Debug] [Connection] Attacker connected: 218.90.121.229 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-07 14:15:13.647 - [Debug] [Auth] Attacker 218.90.121.229 trying to authenticate with 'password'
2024-11-07 14:15:13.649 - [Debug] [Auto Access] Attacker: 218.90.121.229, Threshold: 1, Attempts: 1
2024-11-07 14:15:13.650 - [Debug] [Auto Access] Compromising the honeypot
2024-11-07 14:15:13.650 - [Debug] [Auto Access] Adding the following credentials: 'advit:123456'
2024-11-07 14:15:13.881 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-07 14:15:13.883 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-07 14:15:13.883 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.218
2024-11-07 14:15:13.950 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-07 14:15:14.991 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-07 14:15:18.239 - [Debug] [Connection] Attacker connected: 218.90.121.229 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-07 14:15:19.356 - [Debug] [Auth] Attacker 218.90.121.229 trying to authenticate with 'password'
2024-11-07 14:15:19.356 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-07 14:15:19.357 - [Debug] [Auth] Attacker: 218.90.121.229 has so far made 1 attempts. Remaining: 5 attempts
2024-11-07 14:15:19.822 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
