(node:200442) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-nosession-44678',
  containerIp: '10.0.3.208',
  mitmPort: 44678,
  autoAccessFixed: 1
}
2024-11-13 17:32:29.645 - [Info] MITM Version: 2
2024-11-13 17:32:29.649 - [Info] Auto Access Enabled: true
2024-11-13 17:32:29.650 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-13 17:32:29.662 - [Info] SSH man-in-the-middle server for 10.0.3.208 listening on 10.0.3.1:44678
2024-11-13 17:35:28.202 - [Debug] [Connection] Attacker connected: 218.92.0.211 | Client Identification: SSH-2.0-PuTTY
2024-11-13 17:35:29.485 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'none'
2024-11-13 17:35:29.486 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2024-11-13 17:35:29.895 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'password'
2024-11-13 17:35:29.897 - [Debug] [Auto Access] Attacker: 218.92.0.211, Threshold: 1, Attempts: 1
2024-11-13 17:35:29.897 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Container user is disabled
2024-11-13 17:35:29.898 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 1 attempts. Remaining: 5 attempts
2024-11-13 17:35:30.307 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'password'
2024-11-13 17:35:30.307 - [Debug] [Auto Access] Compromising the honeypot
2024-11-13 17:35:30.308 - [Debug] [Auto Access] Adding the following credentials: 'root:qweasd123'
2024-11-13 17:35:30.462 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-13 17:35:30.464 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-13 17:35:30.465 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.208
2024-11-13 17:35:32.718 - [Debug] [LXC] Authentication Failed
2024-11-13 17:35:32.718 - [Debug] [Auth] Attacker authentication error: Error: All configured authentication methods failed
2024-11-13 17:35:32.719 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 2 attempts. Remaining: 4 attempts
2024-11-13 17:35:32.719 - [Debug] [Auth] Attacker authentication error: Error: All configured authentication methods failed
2024-11-13 17:35:32.719 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 3 attempts. Remaining: 3 attempts
2024-11-13 17:35:32.722 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-13 17:35:32.723 - [Debug] [LXC] Container's OpenSSH server closed connection
2024-11-13 17:35:34.170 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'password'
2024-11-13 17:35:34.171 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-13 17:35:34.171 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 4 attempts. Remaining: 2 attempts
2024-11-13 17:35:35.580 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'password'
2024-11-13 17:35:35.581 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-13 17:35:35.582 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 5 attempts. Remaining: 1 attempts
2024-11-13 17:35:36.989 - [Debug] [Auth] Attacker 218.92.0.211 trying to authenticate with 'password'
2024-11-13 17:35:36.990 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-13 17:35:36.990 - [Debug] [Auth] Attacker: 218.92.0.211 has so far made 6 attempts. Remaining: 0 attempts
2024-11-13 17:35:36.990 - [Debug] [Connection] Max Login Attempts Reached - Closing connection on attacker
2024-11-13 17:35:36.991 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
