(node:3540363) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-session-42135',
  containerIp: '10.0.3.93',
  mitmPort: 42135,
  autoAccessFixed: 1
}
2024-11-08 06:38:55.442 - [Info] MITM Version: 2
2024-11-08 06:38:55.445 - [Info] Auto Access Enabled: true
2024-11-08 06:38:55.447 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-08 06:38:55.459 - [Info] SSH man-in-the-middle server for 10.0.3.93 listening on 10.0.3.1:42135
2024-11-08 06:39:04.865 - [Debug] [Connection] Attacker connected: 161.82.233.179 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-08 06:39:06.492 - [Debug] [Auth] Attacker 161.82.233.179 trying to authenticate with 'password'
2024-11-08 06:39:06.493 - [Debug] [Auto Access] Attacker: 161.82.233.179, Threshold: 1, Attempts: 1
2024-11-08 06:39:06.494 - [Debug] [Auto Access] Compromising the honeypot
2024-11-08 06:39:06.494 - [Debug] [Auto Access] Adding the following credentials: 'deepa:123456'
2024-11-08 06:39:07.018 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-08 06:39:07.020 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-08 06:39:07.020 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.93
2024-11-08 06:39:07.117 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-08 06:39:08.179 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-08 06:39:09.863 - [Debug] [Connection] Attacker connected: 161.82.233.179 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-08 06:39:11.511 - [Debug] [Auth] Attacker 161.82.233.179 trying to authenticate with 'password'
2024-11-08 06:39:11.511 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-08 06:39:11.512 - [Debug] [Auth] Attacker: 161.82.233.179 has so far made 1 attempts. Remaining: 5 attempts
2024-11-08 06:39:12.046 - [Debug] [Connection] Attacker closed the connection
2024-11-08 06:39:12.317 - [Debug] [Connection] Attacker connected: 161.82.233.179 | Client Identification: SSH-2.0-libssh_0.9.6
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
