(node:3118625) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-session-41992',
  containerIp: '10.0.3.43',
  mitmPort: 41992,
  autoAccessFixed: 1
}
2024-11-08 02:26:22.100 - [Info] MITM Version: 2
2024-11-08 02:26:22.102 - [Info] Auto Access Enabled: true
2024-11-08 02:26:22.102 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-08 02:26:22.119 - [Info] SSH man-in-the-middle server for 10.0.3.43 listening on 10.0.3.1:41992
2024-11-08 02:31:08.095 - [Debug] [Connection] Attacker connected: 221.229.218.50 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-08 02:31:09.483 - [Debug] [Auth] Attacker 221.229.218.50 trying to authenticate with 'password'
2024-11-08 02:31:09.485 - [Debug] [Auto Access] Attacker: 221.229.218.50, Threshold: 1, Attempts: 1
2024-11-08 02:31:09.486 - [Debug] [Auto Access] Compromising the honeypot
2024-11-08 02:31:09.487 - [Debug] [Auto Access] Adding the following credentials: 'carha:carha'
2024-11-08 02:31:09.841 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-08 02:31:09.843 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-08 02:31:09.844 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.43
2024-11-08 02:31:09.933 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-08 02:31:11.364 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-08 02:31:12.801 - [Debug] [Connection] Attacker connected: 221.229.218.50 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-08 02:31:15.093 - [Debug] [Auth] Attacker 221.229.218.50 trying to authenticate with 'password'
2024-11-08 02:31:15.093 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-08 02:31:15.094 - [Debug] [Auth] Attacker: 221.229.218.50 has so far made 1 attempts. Remaining: 5 attempts
2024-11-08 02:31:15.577 - [Debug] [Connection] Attacker closed the connection
2024-11-08 02:31:16.789 - [Debug] [Connection] Attacker connected: 221.229.218.50 | Client Identification: SSH-2.0-libssh_0.9.6
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
