(node:284567) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'banner-session-41037',
  containerIp: '10.0.3.252',
  mitmPort: 41037,
  autoAccessFixed: 1
}
2024-11-06 21:28:28.461 - [Info] MITM Version: 2
2024-11-06 21:28:28.463 - [Info] Auto Access Enabled: true
2024-11-06 21:28:28.463 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-06 21:28:28.485 - [Info] SSH man-in-the-middle server for 10.0.3.252 listening on 10.0.3.1:41037
2024-11-06 21:28:40.385 - [Debug] [Connection] Attacker connected: 185.255.91.145 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 21:28:41.545 - [Debug] [Auth] Attacker 185.255.91.145 trying to authenticate with 'password'
2024-11-06 21:28:41.547 - [Debug] [Auto Access] Attacker: 185.255.91.145, Threshold: 1, Attempts: 1
2024-11-06 21:28:41.547 - [Debug] [Auto Access] Compromising the honeypot
2024-11-06 21:28:41.547 - [Debug] [Auto Access] Adding the following credentials: 'ou:ouou'
2024-11-06 21:28:41.830 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-06 21:28:41.832 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-06 21:28:41.832 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.252
2024-11-06 21:28:41.939 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-06 21:28:42.657 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-06 21:28:43.857 - [Debug] [Connection] Attacker connected: 185.255.91.145 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 21:28:44.991 - [Debug] [Auth] Attacker 185.255.91.145 trying to authenticate with 'password'
2024-11-06 21:28:44.991 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-06 21:28:44.992 - [Debug] [Auth] Attacker: 185.255.91.145 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 21:28:45.354 - [Debug] [Connection] Attacker closed the connection
2024-11-06 21:28:45.557 - [Debug] [Connection] Attacker connected: 185.255.91.145 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 21:28:46.728 - [Debug] [Auth] Attacker 185.255.91.145 trying to authenticate with 'password'
2024-11-06 21:28:46.729 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-06 21:28:46.729 - [Debug] [Auth] Attacker: 185.255.91.145 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
