(node:3264163) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-session-40627',
  containerIp: '10.0.3.249',
  mitmPort: 40627,
  autoAccessFixed: 1
}
2024-11-06 09:11:33.360 - [Info] MITM Version: 2
2024-11-06 09:11:33.362 - [Info] Auto Access Enabled: true
2024-11-06 09:11:33.363 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-06 09:11:33.375 - [Info] SSH man-in-the-middle server for 10.0.3.249 listening on 10.0.3.1:40627
2024-11-06 09:14:48.777 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:14:49.540 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:14:49.542 - [Debug] [Auto Access] Attacker: 159.89.154.119, Threshold: 1, Attempts: 1
2024-11-06 09:14:49.542 - [Debug] [Auto Access] Compromising the honeypot
2024-11-06 09:14:49.542 - [Debug] [Auto Access] Adding the following credentials: 'at:at'
2024-11-06 09:14:49.933 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-06 09:14:49.936 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-06 09:14:49.936 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.249
2024-11-06 09:14:50.058 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-06 09:14:50.338 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-06 09:14:50.866 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:14:51.352 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:14:51.353 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-06 09:14:51.354 - [Debug] [Auth] Attacker: 159.89.154.119 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 09:14:51.520 - [Debug] [Connection] Attacker closed the connection
2024-11-06 09:14:51.568 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:14:52.057 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:14:52.058 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-06 09:14:52.058 - [Debug] [Auth] Attacker: 159.89.154.119 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 09:14:52.205 - [Debug] [Connection] Attacker closed the connection
2024-11-06 09:14:52.348 - [Debug] [Connection] Attacker closed connection
2024-11-06 09:14:52.355 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-06 09:14:52.355 - [Debug] [LXC] Container's OpenSSH server closed connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
