(node:601212) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-session-45712',
  containerIp: '10.0.3.169',
  mitmPort: 45712,
  autoAccessFixed: 1
}
2024-11-16 00:06:35.907 - [Info] MITM Version: 2
2024-11-16 00:06:35.909 - [Info] Auto Access Enabled: true
2024-11-16 00:06:35.909 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-16 00:06:35.927 - [Info] SSH man-in-the-middle server for 10.0.3.169 listening on 10.0.3.1:45712
2024-11-16 00:11:03.951 - [Debug] [Connection] Attacker connected: 120.28.193.113 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-16 00:11:05.408 - [Debug] [Auth] Attacker 120.28.193.113 trying to authenticate with 'password'
2024-11-16 00:11:05.409 - [Debug] [Auto Access] Attacker: 120.28.193.113, Threshold: 1, Attempts: 1
2024-11-16 00:11:05.410 - [Debug] [Auto Access] Compromising the honeypot
2024-11-16 00:11:05.410 - [Debug] [Auto Access] Adding the following credentials: 'httpd:1234'
2024-11-16 00:11:05.647 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-16 00:11:05.650 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-16 00:11:05.650 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.169
2024-11-16 00:11:05.741 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-16 00:11:06.766 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-16 00:11:08.257 - [Debug] [Connection] Attacker connected: 120.28.193.113 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-16 00:11:09.715 - [Debug] [Auth] Attacker 120.28.193.113 trying to authenticate with 'password'
2024-11-16 00:11:09.716 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-16 00:11:09.717 - [Debug] [Auth] Attacker: 120.28.193.113 has so far made 1 attempts. Remaining: 5 attempts
2024-11-16 00:11:10.224 - [Debug] [Connection] Attacker closed the connection
2024-11-16 00:11:10.472 - [Debug] [Connection] Attacker connected: 120.28.193.113 | Client Identification: SSH-2.0-libssh_0.9.6
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
