(node:1867012) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-session-43905',
  containerIp: '10.0.3.140',
  mitmPort: 43905,
  autoAccessFixed: 1
}
2024-11-12 19:16:04.804 - [Info] MITM Version: 2
2024-11-12 19:16:04.806 - [Info] Auto Access Enabled: true
2024-11-12 19:16:04.806 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-12 19:16:04.817 - [Info] SSH man-in-the-middle server for 10.0.3.140 listening on 10.0.3.1:43905
2024-11-12 19:16:05.768 - [Debug] [Connection] Attacker connected: 170.64.161.18 | Client Identification: SSH-2.0-Go
2024-11-12 19:16:07.435 - [Debug] [Auth] Attacker 170.64.161.18 trying to authenticate with 'none'
2024-11-12 19:16:07.436 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2024-11-12 19:16:07.929 - [Debug] [Auth] Attacker 170.64.161.18 trying to authenticate with 'password'
2024-11-12 19:16:07.930 - [Debug] [Auto Access] Attacker: 170.64.161.18, Threshold: 1, Attempts: 1
2024-11-12 19:16:07.931 - [Debug] [Auto Access] Compromising the honeypot
2024-11-12 19:16:07.931 - [Debug] [Auto Access] Adding the following credentials: 'es:123456'
2024-11-12 19:16:08.549 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-12 19:16:08.551 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-12 19:16:08.552 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.140
2024-11-12 19:16:08.653 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-12 19:16:09.807 - [Debug] [EXEC] Noninteractive mode attacker command: uname -s -v -n -r -m
2024-11-12 19:16:09.846 - [Debug] [Connection] Attacker connected: 170.64.161.18 | Client Identification: SSH-2.0-Go
2024-11-12 19:16:10.802 - [Debug] [Connection] Attacker closed connection
2024-11-12 19:16:10.813 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-12 19:16:10.814 - [Debug] [LXC] Container's OpenSSH server closed connection
2024-11-12 19:16:11.079 - [Debug] [Auth] Attacker 170.64.161.18 trying to authenticate with 'none'
2024-11-12 19:16:11.080 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2024-11-12 19:16:11.559 - [Debug] [Auth] Attacker 170.64.161.18 trying to authenticate with 'password'
2024-11-12 19:16:11.559 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-12 19:16:11.560 - [Debug] [Auth] Attacker: 170.64.161.18 has so far made 1 attempts. Remaining: 5 attempts
2024-11-12 19:16:11.995 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
