(node:3274054) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-session-40630',
  containerIp: '10.0.3.215',
  mitmPort: 40630,
  autoAccessFixed: 1
}
2024-11-06 09:18:13.841 - [Info] MITM Version: 2
2024-11-06 09:18:13.843 - [Info] Auto Access Enabled: true
2024-11-06 09:18:13.843 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-06 09:18:13.855 - [Info] SSH man-in-the-middle server for 10.0.3.215 listening on 10.0.3.1:40630
2024-11-06 09:18:59.504 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:19:00.258 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:19:00.259 - [Debug] [Auto Access] Attacker: 159.89.154.119, Threshold: 1, Attempts: 1
2024-11-06 09:19:00.259 - [Debug] [Auto Access] Compromising the honeypot
2024-11-06 09:19:00.259 - [Debug] [Auto Access] Adding the following credentials: 'bl:bl123'
2024-11-06 09:19:00.641 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-06 09:19:00.645 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-06 09:19:00.645 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.215
2024-11-06 09:19:00.753 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-06 09:19:01.048 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-06 09:19:01.569 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:19:02.057 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:19:02.058 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-06 09:19:02.059 - [Debug] [Auth] Attacker: 159.89.154.119 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 09:19:02.205 - [Debug] [Connection] Attacker closed the connection
2024-11-06 09:19:02.283 - [Debug] [Connection] Attacker connected: 159.89.154.119 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 09:19:02.766 - [Debug] [Auth] Attacker 159.89.154.119 trying to authenticate with 'password'
2024-11-06 09:19:02.766 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-06 09:19:02.767 - [Debug] [Auth] Attacker: 159.89.154.119 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 09:19:02.925 - [Debug] [Connection] Attacker closed the connection
2024-11-06 09:19:03.069 - [Debug] [Connection] Attacker closed connection
2024-11-06 09:19:03.078 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-06 09:19:03.079 - [Debug] [LXC] Container's OpenSSH server closed connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
