(node:3905634) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-session-40853',
  containerIp: '10.0.3.153',
  mitmPort: 40853,
  autoAccessFixed: 1
}
2024-11-06 14:58:45.712 - [Info] MITM Version: 2
2024-11-06 14:58:45.716 - [Info] Auto Access Enabled: true
2024-11-06 14:58:45.717 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-06 14:58:45.729 - [Info] SSH man-in-the-middle server for 10.0.3.153 listening on 10.0.3.1:40853
2024-11-06 14:59:09.277 - [Debug] [Connection] Attacker connected: 23.146.184.79 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 14:59:09.737 - [Debug] [Auth] Attacker 23.146.184.79 trying to authenticate with 'password'
2024-11-06 14:59:09.739 - [Debug] [Auto Access] Attacker: 23.146.184.79, Threshold: 1, Attempts: 1
2024-11-06 14:59:09.739 - [Debug] [Auto Access] Compromising the honeypot
2024-11-06 14:59:09.741 - [Debug] [Auto Access] Adding the following credentials: 'ss:ss'
2024-11-06 14:59:10.071 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-06 14:59:10.073 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-06 14:59:10.073 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.153
2024-11-06 14:59:10.166 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-06 14:59:10.376 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-06 14:59:13.685 - [Debug] [Connection] Attacker connected: 23.146.184.79 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 14:59:13.903 - [Debug] [Auth] Attacker 23.146.184.79 trying to authenticate with 'password'
2024-11-06 14:59:13.904 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-06 14:59:13.905 - [Debug] [Auth] Attacker: 23.146.184.79 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 14:59:14.004 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
