(node:3060066) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-nosession-45945',
  containerIp: '10.0.3.240',
  mitmPort: 45945,
  autoAccessFixed: 1
}
2024-11-17 21:24:26.322 - [Info] MITM Version: 2
2024-11-17 21:24:26.324 - [Info] Auto Access Enabled: true
2024-11-17 21:24:26.328 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-17 21:24:26.342 - [Info] SSH man-in-the-middle server for 10.0.3.240 listening on 10.0.3.1:45945
2024-11-17 21:25:22.845 - [Debug] [Connection] Attacker connected: 146.190.136.122 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:25:23.314 - [Debug] [Auth] Attacker 146.190.136.122 trying to authenticate with 'password'
2024-11-17 21:25:23.315 - [Debug] [Auto Access] Attacker: 146.190.136.122, Threshold: 1, Attempts: 1
2024-11-17 21:25:23.315 - [Debug] [Auto Access] Compromising the honeypot
2024-11-17 21:25:23.315 - [Debug] [Auto Access] Adding the following credentials: 'arkserver:password'
2024-11-17 21:25:23.598 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-17 21:25:23.601 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-17 21:25:23.601 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.240
2024-11-17 21:25:23.698 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-17 21:25:24.069 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-17 21:25:24.579 - [Debug] [Connection] Attacker connected: 146.190.136.122 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:25:25.050 - [Debug] [Auth] Attacker 146.190.136.122 trying to authenticate with 'password'
2024-11-17 21:25:25.051 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-17 21:25:25.052 - [Debug] [Auth] Attacker: 146.190.136.122 has so far made 1 attempts. Remaining: 5 attempts
2024-11-17 21:25:25.237 - [Debug] [Connection] Attacker closed the connection
2024-11-17 21:25:25.307 - [Debug] [Connection] Attacker connected: 146.190.136.122 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:25:25.777 - [Debug] [Auth] Attacker 146.190.136.122 trying to authenticate with 'password'
2024-11-17 21:25:25.777 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-17 21:25:25.778 - [Debug] [Auth] Attacker: 146.190.136.122 has so far made 1 attempts. Remaining: 5 attempts
2024-11-17 21:25:25.966 - [Debug] [Connection] Attacker closed the connection
2024-11-17 21:25:26.105 - [Debug] [Connection] Attacker closed connection
2024-11-17 21:25:26.114 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-17 21:25:26.116 - [Debug] [LXC] Container's OpenSSH server closed connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
