(node:1669323) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-nosession-43833',
  containerIp: '10.0.3.71',
  mitmPort: 43833,
  autoAccessFixed: 1
}
2024-11-12 15:41:10.050 - [Info] MITM Version: 2
2024-11-12 15:41:10.052 - [Info] Auto Access Enabled: true
2024-11-12 15:41:10.052 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-12 15:41:10.081 - [Info] SSH man-in-the-middle server for 10.0.3.71 listening on 10.0.3.1:43833
2024-11-12 15:42:49.220 - [Debug] [Connection] Attacker connected: 218.92.0.213 | Client Identification: SSH-2.0-PuTTY
2024-11-12 15:42:50.554 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'none'
2024-11-12 15:42:50.554 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2024-11-12 15:42:50.975 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'password'
2024-11-12 15:42:50.977 - [Debug] [Auto Access] Attacker: 218.92.0.213, Threshold: 1, Attempts: 1
2024-11-12 15:42:50.977 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Container user is disabled
2024-11-12 15:42:50.978 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 1 attempts. Remaining: 5 attempts
2024-11-12 15:42:51.401 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'password'
2024-11-12 15:42:51.401 - [Debug] [Auto Access] Compromising the honeypot
2024-11-12 15:42:51.401 - [Debug] [Auto Access] Adding the following credentials: 'root:redhat123'
2024-11-12 15:42:51.647 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-12 15:42:51.649 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-12 15:42:51.649 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.71
2024-11-12 15:42:54.449 - [Debug] [LXC] Authentication Failed
2024-11-12 15:42:54.449 - [Debug] [Auth] Attacker authentication error: Error: All configured authentication methods failed
2024-11-12 15:42:54.450 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 2 attempts. Remaining: 4 attempts
2024-11-12 15:42:54.450 - [Debug] [Auth] Attacker authentication error: Error: All configured authentication methods failed
2024-11-12 15:42:54.450 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 3 attempts. Remaining: 3 attempts
2024-11-12 15:42:54.456 - [Debug] [LXC] Container's OpenSSH server ended connection
2024-11-12 15:42:54.458 - [Debug] [LXC] Container's OpenSSH server closed connection
2024-11-12 15:42:55.913 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'password'
2024-11-12 15:42:55.914 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-12 15:42:55.914 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 4 attempts. Remaining: 2 attempts
2024-11-12 15:42:57.334 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'password'
2024-11-12 15:42:57.335 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-12 15:42:57.336 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 5 attempts. Remaining: 1 attempts
2024-11-12 15:42:58.757 - [Debug] [Auth] Attacker 218.92.0.213 trying to authenticate with 'password'
2024-11-12 15:42:58.757 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-12 15:42:58.758 - [Debug] [Auth] Attacker: 218.92.0.213 has so far made 6 attempts. Remaining: 0 attempts
2024-11-12 15:42:58.758 - [Debug] [Connection] Max Login Attempts Reached - Closing connection on attacker
2024-11-12 15:42:58.759 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
