(node:1212904) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-nosession-41359',
  containerIp: '10.0.3.141',
  mitmPort: 41359,
  autoAccessFixed: 1
}
2024-11-07 06:29:17.054 - [Info] MITM Version: 2
2024-11-07 06:29:17.059 - [Info] Auto Access Enabled: true
2024-11-07 06:29:17.060 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-07 06:29:17.072 - [Info] SSH man-in-the-middle server for 10.0.3.141 listening on 10.0.3.1:41359
2024-11-07 06:30:38.350 - [Debug] [Connection] Attacker connected: 59.12.160.91 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-07 06:30:39.591 - [Debug] [Auth] Attacker 59.12.160.91 trying to authenticate with 'password'
2024-11-07 06:30:39.592 - [Debug] [Auto Access] Attacker: 59.12.160.91, Threshold: 1, Attempts: 1
2024-11-07 06:30:39.593 - [Debug] [Auto Access] Compromising the honeypot
2024-11-07 06:30:39.593 - [Debug] [Auto Access] Adding the following credentials: 'git:gogs'
2024-11-07 06:30:39.962 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-07 06:30:39.964 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-07 06:30:39.964 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.141
2024-11-07 06:30:40.057 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-07 06:30:40.948 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-07 06:30:42.284 - [Debug] [Connection] Attacker connected: 59.12.160.91 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-07 06:30:43.559 - [Debug] [Auth] Attacker 59.12.160.91 trying to authenticate with 'password'
2024-11-07 06:30:43.559 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-07 06:30:43.560 - [Debug] [Auth] Attacker: 59.12.160.91 has so far made 1 attempts. Remaining: 5 attempts
2024-11-07 06:30:44.010 - [Debug] [Connection] Attacker closed the connection
2024-11-07 06:30:44.191 - [Debug] [Connection] Attacker connected: 59.12.160.91 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-07 06:30:45.399 - [Debug] [Auth] Attacker 59.12.160.91 trying to authenticate with 'password'
2024-11-07 06:30:45.400 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-07 06:30:45.401 - [Debug] [Auth] Attacker: 59.12.160.91 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
