(node:3031645) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-nosession-45939',
  containerIp: '10.0.3.101',
  mitmPort: 45939,
  autoAccessFixed: 1
}
2024-11-17 21:02:24.984 - [Info] MITM Version: 2
2024-11-17 21:02:24.986 - [Info] Auto Access Enabled: true
2024-11-17 21:02:24.986 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-17 21:02:24.998 - [Info] SSH man-in-the-middle server for 10.0.3.101 listening on 10.0.3.1:45939
2024-11-17 21:12:48.725 - [Debug] [Connection] Attacker connected: 89.183.192.89 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:12:49.552 - [Debug] [Auth] Attacker 89.183.192.89 trying to authenticate with 'password'
2024-11-17 21:12:49.553 - [Debug] [Auto Access] Attacker: 89.183.192.89, Threshold: 1, Attempts: 1
2024-11-17 21:12:49.553 - [Debug] [Auto Access] Compromising the honeypot
2024-11-17 21:12:49.553 - [Debug] [Auto Access] Adding the following credentials: 'test:ABCabc123'
2024-11-17 21:12:49.796 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-17 21:12:49.799 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-17 21:12:49.799 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.101
2024-11-17 21:12:49.871 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-17 21:12:50.466 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-17 21:12:51.330 - [Debug] [Connection] Attacker connected: 89.183.192.89 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:12:52.192 - [Debug] [Auth] Attacker 89.183.192.89 trying to authenticate with 'password'
2024-11-17 21:12:52.193 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-17 21:12:52.194 - [Debug] [Auth] Attacker: 89.183.192.89 has so far made 1 attempts. Remaining: 5 attempts
2024-11-17 21:12:52.485 - [Debug] [Connection] Attacker closed the connection
2024-11-17 21:12:52.616 - [Debug] [Connection] Attacker connected: 89.183.192.89 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-17 21:12:53.451 - [Debug] [Auth] Attacker 89.183.192.89 trying to authenticate with 'password'
2024-11-17 21:12:53.452 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-17 21:12:53.453 - [Debug] [Auth] Attacker: 89.183.192.89 has so far made 1 attempts. Remaining: 5 attempts
2024-11-17 21:12:53.749 - [Debug] [Connection] Attacker closed the connection
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
